feat: use getopt, consistent -c handling for all cmd modes
PR1823 highlighted the reasoning behind our decision to invoke
commands following the `--` delimiter, and further established
this as exactly equivalent to the `-c` argument handling provided
by all shells. This patch implements this same handling natively
within the `activate` script, making it possible to invoke commands
using either of the `--` or `-c` notations in any of the `--turbo`,
`--noprofile`, or normal "cmd" modes.

diff --git a/assets/activation-scripts/activate b/assets/activation-scripts/activate
--- a/assets/activation-scripts/activate
+++ b/assets/activation-scripts/activate
@@ -3,6 +3,7 @@
 export _coreutils="@coreutils@"
 export _gnused="@gnused@"
 export _setsid="@setsid@"
+export _getopt="@getopt@"
 export _process_compose="@process-compose@"
 export _jq="@jq@"
 export _zdotdir="@out@/activate.d/zdotdir"
@@ -94,11 +95,73 @@ start_services_blocking () {
   fi
 }
 
+# Parse command-line arguments.
+# shellcheck disable=SC1091
+OPTIONS=c:
+LONGOPTS=turbo,noprofile
+USAGE="Usage: $0 [-c \"<cmd> <args>\"] [--turbo] [--noprofile]"
 
-# TODO: add getopt arg parser for following args:
-# -c "<cmd> <args>": specify exact command args to pass to shell
-# --turbo: invoke commands directly without involving userShell
-# --noprofile: do not source `[profile]` scripts
+PARSED=$("$_getopt/bin/getopt" --options="$OPTIONS" --longoptions="$LONGOPTS" --name "$0" -- "$@")
+# shellcheck disable=SC2181
+if [[ $? -ne 0 ]]; then
+  echo "Failed to parse options."
+  exit 1
+fi
+
+# Use eval to remove quotes and replace them with spaces.
+eval set -- "$PARSED"
+
+# Set default values for options.
+FLOX_CMD=""
+FLOX_TURBO=""
+FLOX_NO_PROFILES=""
+while true; do
+  case "$1" in
+    -c)
+      shift
+      if [ -z "$1" ]; then
+	echo "Option -c requires an argument." >&2
+	echo "$USAGE" >&2
+	exit 1
+      fi
+      FLOX_CMD="$1"
+      shift
+      ;;
+    --turbo)
+      FLOX_TURBO="true"
+      shift
+      ;;
+    --noprofile)
+      FLOX_NO_PROFILES="true"
+      shift
+      ;;
+    --)
+      shift
+      break
+      ;;
+    -*)
+      echo "Invalid option: $1" >&2
+      echo "$USAGE" >&2
+      exit 1
+      ;;
+  esac
+done
+
+# Convert the provided command string into an array of arguments in "$@".
+# Henceforth in the script it is assumed that these are the arguments to be
+# invoked either by this shell (with FLOX_TURBO) or with the chosen userShell.
+if [ -n "$FLOX_CMD" ]; then
+  # Throw an error if passed additional arguments along with the -c arg.
+  if [ $# -gt 0 ]; then
+    echo "Unexpected arguments provided with -c argument: $*" >&2
+    echo "$USAGE" >&2
+    exit 1
+  fi
+
+  # Use eval to remove quotes and replace them with spaces as we set $@ to
+  # reflect the command to be invoked.
+  eval set -- "$FLOX_CMD"
+fi
 
 # Set FLOX_ENV as the path by which all flox scripts can make reference to
 # the environment to which they belong. Use this to define the path to the
@@ -298,63 +361,51 @@ if [ $# -gt 0 ]; then
   if [ -n "$FLOX_TURBO" ]; then
     # "turbo command" mode: simply exec the provided command and args
     # without paying the cost of invoking the userShell.
-    if [ "$1" = "-c" ]; then
-      exec bash --noprofile --norc "$@"
-    else
-      exec "$@"
-    fi
-  fi
-  if [ $# -ne 2 ] || [ "$1" != "-c" ]; then
-    # Marshal the provided args into a single safely-quoted string.
-    # We use the magic "${@@Q}" parameter transformation to return
-    # each element of "$@" as a safely quoted string.
-    declare -a cmdarray=()
-    cmdarray=("-c" "${@@Q}")
-    set -- "${cmdarray[@]}"
+    exec "$@"
   fi
   # "-c" command mode: pass both [2] arguments unaltered to shell invocation
   case "$_flox_shell" in
     *bash)
       if [ -n "$FLOX_NO_PROFILES" ]; then
-        exec "$_flox_shell" --noprofile --norc "$@"
+        exec "$_flox_shell" --noprofile --norc -c "$*"
       else
         if [ -t 1 ]; then
-          exec "$_flox_shell" --noprofile --rcfile "$FLOX_ENV/activate.d/bash" "$@"
+          exec "$_flox_shell" --noprofile --rcfile "$FLOX_ENV/activate.d/bash" -c "$*"
         else
           # The bash --rcfile option only works for interactive shells
           # so we need to cobble together our own means of sourcing our
           # startup script for non-interactive shells.
-          exec "$_flox_shell" --noprofile --norc -s <<< "source $FLOX_ENV/activate.d/bash && $2"
+          exec "$_flox_shell" --noprofile --norc -s <<< "source $FLOX_ENV/activate.d/bash && $*"
         fi
       fi
       ;;
     *fish)
       if [ -n "$FLOX_NO_PROFILES" ]; then
-        exec "$_flox_shell" "$@"
+        exec "$_flox_shell" -c "$*"
       else
-        exec "$_flox_shell" --init-command "set -gx _flox_activate_tracelevel $_flox_activate_tracelevel; source $FLOX_ENV/activate.d/fish" "$@"
+        exec "$_flox_shell" --init-command "set -gx _flox_activate_tracelevel $_flox_activate_tracelevel; source $FLOX_ENV/activate.d/fish" -c "$*"
       fi
       ;;
     *tcsh)
       if [ -n "$FLOX_NO_PROFILES" ]; then
-        exec "$_flox_shell" "$@"
+        exec "$_flox_shell" -c "$*"
       else
         export FLOX_ORIG_HOME="$HOME"
         export HOME="$_tcsh_home"
         export FLOX_TCSH_INIT_SCRIPT="$FLOX_ENV/activate.d/tcsh"
-        exec "$_flox_shell" -m "$@"
+        exec "$_flox_shell" -m -c "$*"
       fi
       ;;
     *zsh)
       if [ -n "$FLOX_NO_PROFILES" ]; then
-        exec "$_flox_shell" -o NO_GLOBAL_RCS -o NO_RCS "$@"
+        exec "$_flox_shell" -o NO_GLOBAL_RCS -o NO_RCS -c "$*"
       else
         export FLOX_ORIG_ZDOTDIR="$ZDOTDIR"
         export ZDOTDIR="$_zdotdir"
         export FLOX_ZSH_INIT_SCRIPT="$FLOX_ENV/activate.d/zsh"
         # The "NO_GLOBAL_RCS" option is necessary to prevent zsh from
         # automatically sourcing /etc/zshrc et al.
-        exec "$_flox_shell" -o NO_GLOBAL_RCS "$@"
+        exec "$_flox_shell" -o NO_GLOBAL_RCS -c "$*"
       fi
       ;;
     *)
